# Enable default IP firewall behavior to accept all traffic unless defined by rules
net.inet.ip.fw.default_to_accept=1

# Load the SIFTR driver (for specific hardware support)
siftr_load="YES"

# Set VGA to text mode for console display
hw.vga.textmode="1"
