gateway_enable="YES"
hostname="router"
ifconfig_em0="DHCP"
ifconfig_em1="192.168.1.1/24"
ifconfig_em2="192.168.2.1/24"
ifconfig_em3="192.168.3.1/24"

keymap="us.iso"
sshd_enable="YES"

firewall_enable="YES"
firewall_type="/etc/ipfw.rules"
firewall_script=""

dummynet_enable="YES"


# Adding two static routes
static_routes="lan3 lan4 lan5"
route_lan3="-net 192.168.3.0/24 192.168.3.1"
route_lan4="-net 192.168.1.0/24 192.168.1.1"
route_lan5="-net 192.168.2.0/24 192.168.2.1"