hostname="server"
ifconfig_em0="DHCP"
ifconfig_em1="192.168.3.2/24"
defaultrouter="192.168.3.1"

sshd_enable="YES"
# Set dumpdev to "AUTO" to enable crash dumps, "NO" to disable
dumpdev="AUTO"
firewall_enable="YES"
firewall_type="/etc/ipfw.rules"
#firewall_type="open"
gateway_enable="YES"

ipfw_load="YES"
ipfw_nat_load="YES"

sendmail_enable="NONE"
sendmail_msp_queue_enable="NO"
sendmail_outbound_enable="NO"
sendmail_submit_enable="NO"

static_routes="lan1"
route_lan1="-net 192.168.1.0/24 192.168.3.1"



